name: Convert

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"

permissions:
  actions: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'yesokay666/filter'
          persist-credentials: false
          fetch-depth: 0

      - name: Download and Set Up sing-box
        run: |
          mkdir -p tmp/convert
          wget -O sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.11.5/sing-box-1.11.5-linux-amd64.tar.gz
          tar zxvf sing-box.tar.gz && rm sing-box.tar.gz
          cp sing-box-1.11.5-linux-amd64/sing-box tmp/convert/
          rm -r sing-box-1.11.5-linux-amd64

      - name: Fetch AdGuard DNS Filter Lists
        run: |
          wget -O tmp/convert/AdGuardDNS.txt https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
          wget -O tmp/convert/AdGuardMobile.txt https://cdn.jsdelivr.net/gh/AdguardTeam/AdguardFilters@master/MobileFilter/sections/specific_app.txt
          wget -O tmp/convert/uBlockAds.txt https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssets@gh-pages/filters/filters.min.txt
          wget -O tmp/convert/uBlockPrivacy.txt https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssets@gh-pages/filters/privacy.min.txt
          wget -O tmp/convert/uBlockBadwarerisks.txt https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssets@gh-pages/filters/badware.txt
          wget -O tmp/convert/uBlockQuickfixes.txt https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssets@gh-pages/filters/quick-fixes.txt
          wget -O tmp/convert/uBlockUnbreak.txt https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssets@gh-pages/filters/unbreak.txt
          wget -O tmp/convert/EasyListAds.txt https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssets@gh-pages/thirdparties/easylist.txt
          wget -O tmp/convert/EasyPrivacy.txt https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssets@gh-pages/thirdparties/easyprivacy.txt
          wget -O tmp/convert/NoCoin.txt https://cdn.jsdelivr.net/gh/hoshsadiq/adblock-nocoin-list@master/hosts.txt

      - name: Convert with sing-box
        run: |
          cd tmp/convert
          for file in *.txt; do
            ./sing-box rule-set convert "$file" --output "${file%.txt}.srs" --type adguard
          done
          cd ../..
          mkdir -p output/sing-box/
          rm -rf output/sing-box/* || true
          cp tmp/convert/*.srs output/sing-box/
          rm -r tmp && ls -l output/sing-box

      - name: Check and Commit
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          if git diff --cached --exit-code; then
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV
            git commit -m "actions: Update adguard type srs" -a
          fi

      - name: Push
        if: env.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
